homeassistant:
  name: HASS QuestDB Writer Development
  unit_system: metric
  time_zone: Europe/Paris

default_config:

logger:
  default: info
  logs:
    custom_components.hass_questdb_writer: debug

input_boolean:
  questdb_test:
    name: QuestDB test
